# https://docs.netlify.com/configure-builds/file-based-configuration/#functions

[build]
  publish = "."

  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"

[redirects]
  from = "/planet/*"
  to = "/.netlify/functions/fetch-swapi"
  status = 200