# https://docs.netlify.com/configure-builds/file-based-configuration/#functions

[build]
  publish = "."
  functions = "netlify/functions/swapi"
  functions = "netlify/functions/"

[functions]
  node_bundler = "esbuild"